# Generated by Django 6.0.2 on 2026-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='socials/'),
        ),
    ]
