# Generated by Django 6.0.2 on 2026-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_chatcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_time', models.FloatField(default=0)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('section', 'date')},
            },
        ),
    ]
